version: '3.1'

services:

  spider-flow:
    image: amazoncorretto:8
    restart: always
    working_dir: /app
    environment:
      TZ: Asia/Shanghai
      SELENIUM_DRIVER_CHROME: http://selenium-chrome:4444/wd/hub
    volumes:
      - ./data:/data/spider:rw
      - ./spider-flow-web/target/spider-flow.jar:/app/app.jar
    entrypoint: java -jar app.jar --spring.datasource.username=root --spring.datasource.password=369258 --spring.datasource.url=jdbc:mysql://mysql:3306/spiderflow?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true
    ports:
      - "8088:8088"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 369258
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "13306:8080"
    depends_on:
      - mysql

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 369258
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 369258
      ME_CONFIG_MONGODB_URL: mongodb://root:369258@mongo:27017/admin
    ports:
      - "8017:8081"
    depends_on:
      - mongo

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  selenium-chrome:
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"