version: '3.1'

services:

  spider-flow:
    image: amazoncorretto:8
    restart: always
    working_dir: /app
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/data/spider:rw
      - ./spider-flow-web/target/spider-flow.jar:/app/app.jar
    entrypoint: java -jar app.jar --spring.datasource.username=root --spring.datasource.password=369258 --spring.datasource.url=jdbc:mysql://mysql:3306/spiderflow?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true
    ports:
      - "8088:8088"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 369258
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "13306:8080"
    depends_on:
      - mysql

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 369258
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 369258
      ME_CONFIG_MONGODB_URL: mongodb://root:369258@mongo:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

#  chrome:
#    image: selenium/node-chrome:4.8.1-20230306
#    shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#
#  selenium-hub:
#    image: selenium/hub:4.8.1-20230306
#    container_name: selenium-hub
#    ports:
#      - "4442:4442"
#      - "4443:4443"